baseurl = "http://iany.me/"
languageCode = "en-us"
title = "~iany/blog"
theme = "hpstr"
disqusShortname = "ianyblog"

[permalinks]
post = "/:year/:month/:filename/"
page = "/:filename/"
life = "/life/:year/:month/:filename/"
game = "/games/:year/:month/:filename/"
journal = "/journal/:year/:month/:filename/"

[params.author]
name = "ian"
