baseurl = "http://iany.me/"
defaultContentLanguage = "en"
hasCJKLanguage = true
description = "Personal Blog"
copyright = "Except where otherwise noted, content on this site is licensed under CC-BY-SA"
title = "~iany/blog"
theme = "hpstr"
disqusShortname = "ianyblog"
footnoteReturnLinkContents = "↩"
enableRobotsTXT = true

[permalinks]
post = "/:year/:month/:filename/"
page = "/:filename/"
life = "/life/:year/:month/:filename/"
game = "/games/:year/:month/:filename/"
journal = "/journal/:year/:month/:slug/"

[Taxonomies]
tag = "tags"
series = "series"

[params]
hiddenSections = ["page", "archive", "life"]
cdn = "//cdn.iany.me"

[params.sections.post]
icon = "laptop"
[params.sections.life]
icon = "leaf"
[params.sections.journal]
icon = "list-alt"
[params.sections.game]
icon = "gamepad"

[params.author]
name = "ian"
bio = "Programmer, Husband, Father"
avatar = "images/avatar.jpg"
email = "me@iany.me"
twitter = "doitian"
github = "doitian"

[Languages.zh]
copyright = "除特别说明，所有内容使用署名-相同方式共享 (CC-BY-SA)"
description = "个人博客"
title = "~iany 博客"
languageName = "中文"
disqusShortname = "ianyblogcn"

[Languages.en]
languageName = "English"
